//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveUpdateForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesofCar
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string VIN { get; set; }
        public string LicencePlateNumber { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
